project:
  type: website

website:
  title: "MReye demos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: paros.qmd
        text: PAROS
      - href: visisipy.qmd
        text: Visisipy
      - href: https://mreye.nl
        text: About us


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true



