project:
  type: website
  pre-render: python _scripts/generate-edit-url.py
  resources:
    - "edit.html"

website:
  title: "MReye demos"
  description: "Interactive demos of research projects by the MReye group"
  favicon: _assets/icon.png
  site-url: https://demo.mreye.nl
  repo-url: https://github.com/MREYE-LUMC/demos
  navbar:
    logo: _assets/icon.png
    left:
      - href: paros/index.qmd
        text: PAROS
      - href: visisipy/index.qmd
        text: Visisipy
      - href: https://mreye.nl
        text: About us
    right:
      - icon: github
        href: https://github.com/MREYE-LUMC/demos
        aria-label: GitHub

  page-footer:
    center: "© 2025 Jan-Willem Beenakker and the MReye research group. Built with [Quarto](https://quarto.org) and [Shiny for Python](https://https://shiny.posit.co/py/)."

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true



