project:
  type: website

website:
  title: "MReye demos"
  favicon: _assets/icon.png
  navbar:
    logo: _assets/icon.png
    left:
      - href: paros/index.qmd
        text: PAROS
      - href: visisipy/index.qmd
        text: Visisipy
      - href: https://mreye.nl
        text: About us

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true



