[project]
name = "mreye-demos"
version = "0.1.0"
description = "Website with interactive demos for the MReye research group"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "quarto-cli>=1.7.30",
    "shinylive>=0.8.3",
]
