name: Playwright Tests

on:
  # Allow manual trigger
  workflow_dispatch:
  # Run on pull requests
  pull_request:
    branches:
      - main

  # Run on push to main
  push:
    branches:
      - main

  # Run daily at 07:00 UTC to catch regressions, e.g. due to dependency updates
  schedule:
    - cron: "0 7 * * *" # Every day at 07:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 10
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Build website
        run: pnpm run build

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run Playwright tests
        run: pnpm test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
